name: SimpleEssentials
version: '1.0'
main: de.nitrox.simpleEssentials.SimpleEssentials
api-version: '1.16'
load: STARTUP
authors: [ Nitrox_XD ]
description: Simple Essentials you need for a Minecraft Server
softdepend: [PlaceholderAPI]
